# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: gopa 2020
description: L’Intelligenza Artificiale al servizio del cittadino
baseurl: "/ia.italia.it" # the subpath of your site, e.g. /blog
url: https://ia.italia.it # the base hostname & protocol for your site, e.g. http://example.com
author: Agenzia per l'Italia Digitale
facebook:
  publisher: https://www.facebook.com/Agenzia-per-lItalia-Digitale-1562653967388005/
google:
  analytics: UA-100364858-4
piwik:
  id: 4

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom vars
theme_color: "#0066cc"
css_theme: t-Pac
owner_short: AgID
owner_full: |
  Agenzia per
  l'Italia Digitale
owner_link: http://www.agid.gov.it
logo: /assets/images/logo-ia.svg
owner_logo: /assets/images/agid-logo.svg
owner_logo_alt: /assets/images/agid-logo_alt.svg
pill: beta
lang: it_IT

collections:
  pages:
    output: true
    permalink: /:path/
    layout: page
  press-releases:
    output: false

defaults:
  -
    scope:
      path: "_pages/it"
      type: "pages"
    values:
      permalink: /:title/

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
